config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'books#index'

  get 'find', to: 'pages#find'
  post 'search', to: 'pages#search'

  get 'matches/listed', to: 'pages#giver_match'
  get 'matches/requested', to: 'pages#taker_match'
  get 'matches', to: 'pages#matches'

  resources :books
  resources :requests, only: [:index, :create, :show, :destroy]
  get 'my_books', to: 'books#my_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :requests

  def sara
    alksjflksajdf;aklsdjfkl;as
  end 

  ACCEPTABLE_STATES = %w( listed requested accepted )
  validates_inclusion_of :state, in: ACCEPTABLE_STATES
  
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :giver, :class_name => 'User'
  belongs_to :taker, :class_name => 'User'
  belongs_to :book
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :requests, foreign_key: :giver_id
  has_many :requests, foreign_key: :taker_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :user_has_match?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  def user_has_match?
    user_book_states.include? 'accepted'
  end

  def user_book_states
    current_user.requests.map { |req| req.book.state }
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.where.not(user_id: current_user.id).where(state: 'listed').paginate(page: params[:page], per_page: 5)
  end

  def show
    get_book
  end

  def new
    @book = Book.new(book_params)
  end

  def create
    create_book(params)
    redirect_to my_books_path
  end

  def destroy
    book = Book.find(params[:id])
    book.requests.delete_all
    book.destroy
    flash[:danger] = 'Listing was successfully removed.'
    redirect_to my_books_path
  end

  def update
    book = Book.find(params[:id])
    book.update!(state: params[:state])
    flash[:success] = 'Book request accepted. Please send the user an email.' if book.save
    redirect_to my_books_path
  end

  def my_books
    @books = Book.where(user_id: current_user.id).paginate(page: params[:page], per_page: 5)
  end

  private

  def book_params
    params.permit(:title, :subtitle, :description, :isbn_10, :isbn_13, :text_snippet, :thumbnail, :small_thumbnail, :categories, author: [])
  end

  def get_book
    @book = Book.find(params[:id])
  end

  def create_book(params)
    book_data = params[:book]
    Book.create!(
      title: book_data['title'],
      subtitle: book_data['subtitle'],
      author: book_data['author'],
      description: book_data['description'],
      text_snippet: book_data['text_snippet'],
      thumbnail: book_data['thumbnail'],
      small_thumbnail: book_data['small_thumbnail'],
      isbn_10: book_data['isbn_10'],
      isbn_13: book_data['isbn_13'],
      user: current_user
    )
    flash[:success] = "Your book was successfully listed!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  API_KEY = ENV['GOOGLE_API_KEY']

  def home
  end

  def search
    response = Google.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{params[:isbn]}&key=#{API_KEY}")
    @book = new_book(response)
    redirect_to new_book_path(@book)
  end

  def find
  end

  def add
  end

  def giver_match
    @request = Request.where(giver_id: current_user.id, book_id: params[:book_id], state: 'accepted')
  end

  def taker_match
    @request = Request.where(taker_id: current_user.id, book_id: params[:book_id], state: 'accepted')
  end

  private

  def new_book(json_response)
    response = JSON.parse(json_response)['items'].first
    text_snippet = nil

    if response['searchInfo'].present?
      text_snippet = response['searchInfo']['textSnippet']
    end

    response = response['volumeInfo']

    {
      title: response['title'] || nil,
      subtitle: response['subtitle'] || nil,
      author: response['authors'] || nil,
      description: response['description'] || nil,
      isbn_10: response['industryIdentifiers'].first['identifier'] || nil,
      isbn_13: response['industryIdentifiers'].second['identifier'] || nil,
      thumbnail: response['imageLinks']['thumbnail'] || nil,
      small_thumbnail: response['imageLinks']['smallThumbnail'] || nil,
      text_snippet: text_snippet,
      categories: response['categories'].join(' ')
    }
  end

end

class Google
  include HTTParty
  format :html
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    if Request.where(taker_id: current_user.id).count > 0
      @requests = Request.where(taker_id: current_user.id).paginate(page: params[:page], per_page: 5)
    else
      flash[:warning] = 'Sorry, you do not have any requested books'
      redirect_to root_path
    end
  end

  def show
    @request = Request.includes(:book, :taker, :giver).find_by(giver_id: current_user.id, book_id: params[:id])
  end

  def create
    book = Book.find(params[:book_id])
    giver = book.user
    taker = current_user
    @request = Request.create!(book: book, giver: giver, taker: taker)
    if @request.save
      book.update!(state: 'requested')
      flash[:success] = 'Book request sent.'
    end
    redirect_to requests_path 
  end

  def destroy
    request = Request.includes(:book).find(params[:id])
    request.book.update!(state: 'listed')
    request.destroy!
    flash[:danger] = 'Request for book was cancelled.'
    redirect_to my_books_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.slim
h1 align='center' Available Books
div align='center'
  = will_paginate
div.col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2
  - @books.each do |book|
    div.panel.panel-info
      div.panel-heading
        h2.panel-title= link_to "#{book.title}", book_path(book)
        small by #{book.author}
      div.panel-body
        p #{book.text_snippet}
      div.panel-body
        div.col-s-4.col-s-offset-4.col-xs-6.col-xs-offset-3
          = link_to 'View', book_path(book), class: 'btn btn-md btn-block btn-primary'
div align='center'
  = will_paginate

app/views/books/my_books.html.slim
h1 align='center' Your Listed Books
div align='center'
  = will_paginate
div.col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2
  - @books.each do |book|
    div.panel.panel-primary
      div.panel-heading
        div.row
          div.container
            h2.panel-title= link_to "#{book.title}", book_path(book)
            small by #{book.author}
      - if book.state == 'requested'
        div.panel-body
          div.col-s-4.col-s-offset-4.col-xs-6.col-xs-offset-3
            = link_to 'View Request', request_path(book), class: 'btn btn-md btn-block btn-success'
      - else
        div.panel-body
          div.col-s-4.col-s-offset-4.col-xs-6.col-xs-offset-3
            = link_to 'Remove', book_path(book), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: 'btn btn-md btn-block btn-danger'

div align='center'
  = will_paginate

app/views/books/new.html.slim
div.container
  div.row
    div.col-l-6.col-l-offset-3.col-md-6.col-md-offset-3
      = form_for(@book, :html => {class: 'form-horizontal', role: 'form'}) do |f|
        fieldset
          legend align='center' Confirm Book Details
          div.form-group
            label.col-sm-2.control-label for='title'
              = f.label :title
            div.col-sm-8
              = f.text_field :title, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='subtitle'
              = f.label :subtitle
            div.col-sm-8
              = f.text_field :subtitle, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='author'
              = f.label :author
            div.col-sm-8
              = f.text_field :author, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='description'
              = f.label :description
            div.col-sm-8
              = f.text_area :description, rows: 15, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='text_snippet'
              = f.label :text_snippet
            div.col-sm-8
              = f.text_area :text_snippet, rows: 4, class: 'form-control', readonly: "readonly"

          div.form-group align='center'
            img src="#{@book.thumbnail}"

          div.form-group
            label.col-sm-2.control-label for='thumbnail'
              = f.label :thumbnail
            div.col-sm-8
              = f.text_field :thumbnail, class: 'form-control', readonly: "readonly"

          div.form-group align='center'
            img src="#{@book.small_thumbnail}"

          div.form-group
            label.col-sm-2.control-label for='small_thumbnail'
              = f.label :small_thumbnail
            div.col-sm-8
              = f.text_field :small_thumbnail, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='isbn_10'
              = f.label :isbn_10
            div.col-sm-8
              = f.text_field :isbn_10, class: 'form-control', readonly: "readonly"

          div.form-group
            label.col-sm-2.control-label for='isbn_13'
              = f.label :isbn_13
            div.col-sm-8
              = f.text_field :isbn_13, class: 'form-control', readonly: "readonly"

          div.form-group
            div align='center'
              = f.submit 'Create New Listing', method: :post, class: 'btn btn-primary btn-lg', align: 'center'

app/views/books/show.html.slim
div.col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
  div.panel.panel-info
    div.panel-heading
      div.row
        div.container
          h2.panel-title #{@book.title}
          small by #{@book.author}
    div.panel-body
      div align='center'
        img src="#{@book.thumbnail}"
      div
        p #{@book.description}
    div.panel-footer
      div.btn-group.btn-group-justified
      = link_to 'Request', requests_path({book_id: @book.id}), method: :post, class: 'btn btn-success'
      = link_to 'Return', books_path, class: 'btn btn-danger'

app/views/layouts/_messages.html.slim
div class="row"
  div class="col-xs-10 col-xs-offset-1"
    - flash.each do |name, msg|
      div class="alert alert-#{name}"
        a href="#" class="close" data-dismiss="alert" &#215
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.fixed-top
  div.container-fluid
    div.navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#bs-example-collapse' aria-expandable='false'
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Tsundoku', root_path, class: 'navbar-brand'

    div.collapse.navbar-collapse#bs-example-collapse
      - if user_signed_in?
        ul.nav.navbar-nav
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown"
              | Books
              span.caret
            ul.dropdown-menu role="books"
              li
                = link_to 'Browse Available Books', books_path
              li
                = link_to 'List a Book', find_path
              li.divider
              li
                = link_to 'Your Listed Books', my_books_path
              li
                = link_to 'Your Requested Books', requests_path
              - if user_has_match?
                li I like it a lot

      - if user_signed_in?
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'Sign Out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bookclub
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1"

  body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    div.container#main-background
      = yield

app/views/pages/find.html.slim
h1 align='center' Create a new Book Listing
p align='center' Please type the 10 digit or 13 digit ISBN number.
div.col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
  div.row
    div.col-xs-10.col-xs-offset-1
      = form_tag('/search') do
        div.form-group
          div.control-label.col-sm-2
            = label_tag :isbn
          div.col-sm-8
            = text_field_tag :isbn, '', class: 'form-control', placeholder: 'ISBN', autofocus: true, pattern: '(?:(?=.{17}$)97[89][ -](?:[0-9]+[ -]){2}[0-9]+[ -][0-9]|97[89][0-9]{10}|(?=.{13}$)(?:[0-9]+[ -]){2}[0-9]+[ -][0-9Xx]|[0-9]{9}[0-9Xx])', title: 'Please enter a valid ISBN10 or ISBN13'

        div.form-group#search-button align='center'
          = submit_tag 'Search Isbn', class: "btn btn-primary btn-lg"

app/views/pages/giver_match.html.slim
h1 align='center' Imma taker

app/views/pages/home.html.slim
div.jumbotron
  h1 align="center" Tsundoku
  p Tsundoku is the online marketplace for expats to give away and find books in Japan

app/views/pages/taker_match.html.slim
h1 align='center' Chet Taker

app/views/requests/index.html.slim
h1 align='center' Your Requested Books
div align='center'
  = will_paginate
div.col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2
  - @requests.each do |request|
    div.panel.panel-info
      div.panel-heading
        h2.panel-title= link_to "#{request.book.title}", book_path(request.book)
        small by #{request.book.author}
      div.panel-body
        p #{request.book.text_snippet}
      div.panel-body
        div.col-s-4.col-s-offset-4.col-xs-6.col-xs-offset-3
          = link_to 'View', book_path(request.book), class: 'btn btn-md btn-block btn-primary'
div align='center'
  = will_paginate

app/views/requests/show.html.slim
h1 align='center' Request Details
div.col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2
  div.panel.panel-primary
    div.panel-heading
      h2.panel-title align='center' #{@request.book.title}
    div.panel-body
      p Requested by: #{@request.taker.email}
    div.panel-footer
      div align='center'
        = link_to 'Accept', book_path({book_id: @request.book.id, state: 'accepted'}), method: :put, class: 'btn btn-m btn-success'
        = mail_to "#{@request.taker.email}", "Send Email", class: 'btn btn-s btn-primary'
        = link_to 'Rejected', request_path(@request), method: :delete, class: 'btn btn-m btn-danger'

app/views/shared/_errors.html.slim
- if obj.errors.any?
  div class="row"
    div class="col-xs-8 col-xs-offset-2"
      div class="panel panel-danger"
        div class="panel-heading"
          h2 class="panel-title" align="center" #{pluralize(obj.errors.count, "error")} prohibited this article from being saved
          div class="panel-body"
            ul
              - obj.errors.full_messages.each do |msg|
                li
                  = msg